### ISSUE TITLE
exportOptionsPlist的作用是什么？

### ISSUE THREAD

**Issue by a714857512** [zhang382847657/xcodebuild#1]
exportOptionsPlist的作用是什么？

**Comment by zhang382847657** [comment]
Xcode7之后取消了原来的-exportFormat，而是使用exportOptionsPlist 来取代，具体的使用方法可以在Terminal打xcodebuild --help查看。
我们需要自己创建一个plist作为Export Options，只要有这个配置文件，那我们在使用这个命令的时候就能打出跟手动用Xcode Archive之后export出的ipa一样了，也不会存在无法上传iTunesConnect的问题。

**Export Options Plist**

下面是目前我知道的options的设置:
method: (String) The method of distribution, which can be set as any of the following:

app-store
enterprise
ad-hoc
development
teamID: (String) The development program team identifier.
uploadSymbols: (Boolean) Option to include symbols in the generated ipa file.
uploadBitcode: (Boolean) Option to include Bitcode.

**Plist 样例：**
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">


<dict>
  <key>teamID</key>
        <string>MYTEAMID123</string>
        <key> teamID </key>
        <string>app-store</string>
        <key>uploadSymbols</key>
        <true/>
</dict>


<plist>
```

**Comment by a714857512** [comment]
谢谢解答。已经搞好脚本打包了。
